-- JIMDUR ERP - esquema PostgreSQL para Neon
-- Idempotente: puede ejecutarse más de una vez.

CREATE TABLE IF NOT EXISTS app_users (
  email TEXT PRIMARY KEY,
  username TEXT,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'USUARIO',
  active INTEGER NOT NULL DEFAULT 1,
  permissions TEXT NOT NULL DEFAULT '[]',
  password_hash TEXT,
  password_salt TEXT,
  password_iterations INTEGER NOT NULL DEFAULT 100000,
  must_change_password INTEGER NOT NULL DEFAULT 0,
  password_updated_at TIMESTAMP,
  recovery_key_hash TEXT,
  recovery_key_created_at TIMESTAMP,
  last_access_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS app_users_username_unique
  ON app_users (username);

CREATE TABLE IF NOT EXISTS app_sessions (
  token_hash TEXT PRIMARY KEY,
  user_email TEXT NOT NULL REFERENCES app_users(email) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NOT NULL,
  last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS app_sessions_user_idx ON app_sessions (user_email);
CREATE INDEX IF NOT EXISTS app_sessions_expiry_idx ON app_sessions (expires_at);

CREATE TABLE IF NOT EXISTS auth_rate_limits (
  key TEXT PRIMARY KEY,
  attempts INTEGER NOT NULL DEFAULT 0,
  window_started_at TIMESTAMP NOT NULL,
  locked_until TIMESTAMP
);

CREATE TABLE IF NOT EXISTS warehouses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS warehouses_code_unique ON warehouses (code);
CREATE UNIQUE INDEX IF NOT EXISTS warehouses_legacy_id_unique ON warehouses (legacy_id);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER,
  code TEXT NOT NULL,
  supplier_code TEXT,
  name TEXT NOT NULL,
  brand TEXT,
  application TEXT,
  unit TEXT NOT NULL DEFAULT 'UND',
  location TEXT,
  cost DOUBLE PRECISION NOT NULL DEFAULT 0,
  minimum_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS products_code_unique ON products (code);
CREATE UNIQUE INDEX IF NOT EXISTS products_legacy_id_unique ON products (legacy_id);
CREATE INDEX IF NOT EXISTS products_name_idx ON products (name);

CREATE TABLE IF NOT EXISTS order_product_aliases (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alias TEXT NOT NULL,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  user_email TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS order_product_aliases_alias_unique
  ON order_product_aliases (alias);
CREATE INDEX IF NOT EXISTS order_product_aliases_product_idx
  ON order_product_aliases (product_id);

CREATE TABLE IF NOT EXISTS stock (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id),
  warehouse_id INTEGER NOT NULL REFERENCES warehouses(id),
  physical DOUBLE PRECISION NOT NULL DEFAULT 0,
  reserved DOUBLE PRECISION NOT NULL DEFAULT 0,
  damaged DOUBLE PRECISION NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS stock_product_warehouse_unique
  ON stock (product_id, warehouse_id);
CREATE INDEX IF NOT EXISTS stock_warehouse_idx ON stock (warehouse_id);

CREATE TABLE IF NOT EXISTS movements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  type TEXT NOT NULL,
  document TEXT NOT NULL,
  product_id INTEGER NOT NULL REFERENCES products(id),
  warehouse_id INTEGER NOT NULL REFERENCES warehouses(id),
  quantity DOUBLE PRECISION NOT NULL,
  notes TEXT,
  user_email TEXT
);

CREATE INDEX IF NOT EXISTS movements_date_idx ON movements (occurred_at);
CREATE INDEX IF NOT EXISTS movements_product_idx ON movements (product_id);

CREATE TABLE IF NOT EXISTS receipts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER,
  number TEXT NOT NULL,
  date TEXT NOT NULL,
  warehouse_id INTEGER NOT NULL REFERENCES warehouses(id),
  supplier TEXT,
  source TEXT,
  document_number TEXT,
  carrier TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'CONFIRMADA',
  user_email TEXT,
  confirmed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS receipts_number_unique ON receipts (number);

CREATE TABLE IF NOT EXISTS receipt_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id INTEGER NOT NULL REFERENCES receipts(id),
  product_id INTEGER NOT NULL REFERENCES products(id),
  expected DOUBLE PRECISION NOT NULL DEFAULT 0,
  received DOUBLE PRECISION NOT NULL DEFAULT 0,
  damaged DOUBLE PRECISION NOT NULL DEFAULT 0,
  incident TEXT,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS proformas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER,
  number TEXT NOT NULL,
  date TEXT NOT NULL,
  client TEXT NOT NULL,
  document TEXT,
  address TEXT,
  warehouse_id INTEGER NOT NULL REFERENCES warehouses(id),
  payment_condition TEXT NOT NULL DEFAULT 'CONTADO',
  status TEXT NOT NULL DEFAULT 'VIGENTE',
  user_email TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS proformas_number_unique ON proformas (number);

CREATE TABLE IF NOT EXISTS proforma_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proforma_id INTEGER NOT NULL REFERENCES proformas(id),
  product_id INTEGER NOT NULL REFERENCES products(id),
  quantity DOUBLE PRECISION NOT NULL,
  price DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER,
  number TEXT NOT NULL,
  date TEXT NOT NULL,
  warehouse_id INTEGER NOT NULL REFERENCES warehouses(id),
  destination TEXT NOT NULL DEFAULT 'TIENDA PRINCIPAL',
  order_type TEXT NOT NULL DEFAULT 'REPOSICIÓN',
  flow_mode TEXT NOT NULL DEFAULT 'PEDIDO',
  priority TEXT NOT NULL DEFAULT 'NORMAL',
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'PENDIENTE',
  user_email TEXT,
  started_at TIMESTAMP,
  ready_at TIMESTAMP,
  dispatched_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS orders_number_unique ON orders (number);

CREATE TABLE IF NOT EXISTS order_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id),
  product_id INTEGER NOT NULL REFERENCES products(id),
  requested DOUBLE PRECISION NOT NULL,
  reserved DOUBLE PRECISION NOT NULL DEFAULT 0,
  dispatched DOUBLE PRECISION NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'PENDIENTE',
  notes TEXT
);

CREATE TABLE IF NOT EXISTS transfers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER,
  number TEXT NOT NULL,
  date TEXT NOT NULL,
  origin_warehouse_id INTEGER NOT NULL REFERENCES warehouses(id),
  destination_warehouse_id INTEGER NOT NULL REFERENCES warehouses(id),
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'CONFIRMADA',
  user_email TEXT,
  confirmed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS transfers_number_unique ON transfers (number);

CREATE TABLE IF NOT EXISTS transfer_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_id INTEGER NOT NULL REFERENCES transfers(id),
  product_id INTEGER NOT NULL REFERENCES products(id),
  quantity DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_email TEXT,
  action TEXT NOT NULL,
  module TEXT NOT NULL,
  entity TEXT,
  record_key TEXT,
  detail TEXT
);

CREATE INDEX IF NOT EXISTS audit_date_idx ON audit_logs (occurred_at);

CREATE TABLE IF NOT EXISTS import_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_server TEXT,
  source_database TEXT,
  user_email TEXT,
  summary TEXT NOT NULL
);
